import { ContactDto } from '@/api/get-contact/get-contact.schemas';

export const mockContacts: ContactDto[] = [
  {
    first_name: 'Zachariah',
    last_name: 'Churcher',
    email: null,
    gender: 'Bigender',
    phone: '5307324336',
    note: 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
    telegram: null,
    avatar: 'https://robohash.org/omnisquiet.png?size=300x300&set=set1',
    company: 'Skalith',
    address: '800 Scofield Drive',
    createdAt: 1637996519400,
    updatedAt: 1637996519400,
    id: 1,
  },
  {
    first_name: 'Uta',
    last_name: 'McQuaide',
    email: 'umcquaideb@mtv.com',
    gender: 'Agender',
    phone: '9472537313',
    note: 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.',
    telegram: 'umcquaideb',
    avatar: 'https://robohash.org/explicabononexpedita.png?size=300x300&set=set1',
    company: 'Skilith',
    address: '6 Pond Avenue',
    createdAt: 1637996519400,
    updatedAt: 1637996519400,
    id: 2,
  },
  {
    first_name: 'John',
    last_name: 'Ducker',
    email: null,
    gender: 'Genderfluid',
    phone: '5914128816',
    note: 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.',
    telegram: null,
    avatar: 'https://robohash.org/vitaecumsequi.png?size=300x300&set=set1',
    company: 'Skiptube',
    address: '555 Eggendart Junction',
    createdAt: 1637996519400,
    updatedAt: 1637996519400,
    id: 3,
  },
  {
    first_name: 'Odo',
    last_name: 'Sallan',
    email: 'osalland@washingtonpost.com',
    gender: 'Female',
    phone: '1455203090',
    note: 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.',
    telegram: 'osalland',
    avatar: 'https://robohash.org/omnisfacerenostrum.png?size=300x300&set=set1',
    company: 'Meezzy',
    address: null,
    createdAt: 1637996519400,
    updatedAt: 1637996519400,
    id: 4,
  },
  {
    first_name: 'Julissa',
    last_name: 'Hughesdon',
    email: 'jhughesdone@opera.com',
    gender: 'Genderqueer',
    phone: '1276427742',
    note: 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.',
    telegram: null,
    avatar: 'https://robohash.org/voluptatumnemoassumenda.png?size=300x300&set=set1',
    company: 'Devbug',
    address: null,
    createdAt: 1637996519400,
    updatedAt: 1637996519400,
    id: 5,
  },
  {
    first_name: 'Hildy',
    last_name: 'Spick',
    email: 'hspickf@i2i.jp',
    gender: 'Genderfluid',
    phone: '3868235504',
    note: 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.',
    telegram: null,
    avatar: 'https://robohash.org/quibusdamillonemo.png?size=300x300&set=set1',
    company: 'Realpoint',
    address: null,
    createdAt: 1637996519400,
    updatedAt: 1637996519400,
    id: 6,
  },
  {
    first_name: 'Jacintha',
    last_name: 'Wildblood',
    email: 'jwildbloodg@creativecommons.org',
    gender: 'Agender',
    phone: '6282903552',
    note: 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.',
    telegram: null,
    avatar: 'https://robohash.org/repudiandaequiquas.png?size=300x300&set=set1',
    company: 'Oyoba',
    address: null,
    createdAt: 1637996519400,
    updatedAt: 1637996519400,
    id: 7,
  },
  {
    first_name: 'Holli',
    last_name: 'Emanueli',
    email: null,
    gender: 'Non-binary',
    phone: '6088846153',
    note: 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',
    telegram: 'hemanuelih',
    avatar: 'https://robohash.org/autnisicumque.png?size=300x300&set=set1',
    company: 'Meevee',
    address: '23309 Dorton Terrace',
    createdAt: 1637996519400,
    updatedAt: 1637996519400,
    id: 8,
  },
  {
    first_name: 'Oswell',
    last_name: 'Martinello',
    email: null,
    gender: 'Genderfluid',
    phone: '1858979331',
    note: 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.',
    telegram: 'omartinelloi',
    avatar: 'https://robohash.org/sitsitnemo.png?size=300x300&set=set1',
    company: 'Linkbuzz',
    address: null,
    createdAt: 1637996519400,
    updatedAt: 1637996519400,
    id: 9,
  },
  {
    first_name: 'Veronica',
    last_name: 'Craiker',
    email: null,
    gender: 'Bigender',
    phone: '9316683775',
    note: 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.',
    telegram: null,
    avatar: 'https://robohash.org/quaeratsintdolor.png?size=300x300&set=set1',
    company: 'Gabcube',
    address: '4196 Hanson Park',
    createdAt: 1637996519400,
    updatedAt: 1637996519400,
    id: 10,
  },
  {
    first_name: 'Oswell',
    last_name: 'Martinello',
    email: 'jwildbloodg@creativecommons.org',
    gender: 'Genderfluid',
    phone: '1858979331',
    note: 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.',
    telegram: 'omartinelloi',
    avatar: 'https://robohash.org/sitsitnemo.png?size=300x300&set=set1',
    company: 'Linkbuzz',
    address: '4196 Hanson Park',
    createdAt: 1637996519400,
    updatedAt: 1637996519400,
    id: 11,
  },
  {
    first_name: 'Veronica',
    last_name: 'Craiker',
    gender: 'Bigender',
    phone: '9316683775',
    email: null,
    note: null,
    telegram: null,
    avatar: null,
    company: null,
    address: null,
    createdAt: 1637996519400,
    updatedAt: 1637996519400,
    id: 12,
  },
];

export const mockContactList = {
  data: mockContacts,
  total: mockContacts.length,
  limit: 12,
  skipped: 0,
};
